server:
  port: 8767
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-boot-microservices-realm
      client:
        registration:
          keycloak:
            client-id: boreebeko
            client-secret: V7LPDrEIrfdBHgFjeOvOEM9STPKTaNJJ
            scope: openid
            redirect-uri: http://localhost:8767/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/spring-boot-microservices-realm
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka/
