server:
  port: 8767
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: dynamic-route
          uri: lb://{service-id}
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<path>.*), /${path}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka/
