server:
  port: 8767
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - StripPrefix=1
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka/
