server:
  port: 8091
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-boot-microservices-realm
  kafka:
    consumer:
      auto-offset-reset: earliest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka/
