server:
  port: 8767
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka/

# Actuator endpoints
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Resilience4J Properties
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: "COUNT_BASED"
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: "5s"
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimum-number-of-calls: 5
  timelimiter:
    configs: 
      default:
        timeout-duration: "3s"
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: "2s"
  ratelimiter:
    instances:
      image-service:
        limitForPeriod: 10
        limitRefreshPeriod: "60s"
        
