server:
  port: 8092
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-boot-microservices-realm
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8766/eureka/
