server:
  port: 9000
spring:
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-server:9000
        client:
          gateway-client:
            registration:
              client-id: gateway-client
              client-secret: "{noop}secret"
              client-name: Gateway Client
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://localhost:8080/login/oauth2/code/gateway-client-oidc
                - http://localhost:8080/authorized
              scopes:
                - openid
              
            
